export const twentyQuestions = [
  "What was your first impression of me?",
  "When did you know this was something real?",
  "What's a memory of us you replay often?",
  "What do you need more of from me?",
  "What makes you feel most loved?",
  "What's something you've never told me?",
  "What are you looking forward to most this year?",
  "How have you changed since we met?",
  "What does home mean to you?",
  "What's a small thing I do that you love?",
  "What scares you about the future?",
  "What tradition should we start?",
  "What song describes us?",
  "What do you want to be remembered for?",
  "Where do you feel most yourself?",
  "What's the kindest thing anyone has done for you?",
  "What would your perfect ordinary day look like?",
  "What do you want to learn together?",
  "What are you grateful for right now?",
  "What should we promise each other?",
];
